version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  python:
    build: ./python
    container_name: python_dev
    volumes:
      - ./python/src:/app/src
    depends_on:
      db:
        condition: service_healthy
    user: "${USER_ID}:${GROUP_ID}"
    networks:
      - app-network
    tty: true

networks:
  app-network:
    driver: bridge
